-- Apply during a controlled deployment when AUTO_SYNC=false.
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "organisationType" VARCHAR(64) DEFAULT 'GOVERNMENT';
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "stateCodes" VARCHAR(16)[] DEFAULT ARRAY['ALL'];
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "professionTags" VARCHAR(64)[] DEFAULT ARRAY[]::VARCHAR[];
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "accessModel" VARCHAR(32) DEFAULT 'FREE';
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "verificationSource" VARCHAR(255);
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "verificationStatus" VARCHAR(64) DEFAULT 'PENDING_REVIEW';
ALTER TABLE "GovResources" ADD COLUMN IF NOT EXISTS "lastVerifiedAt" TIMESTAMP WITH TIME ZONE;
